["W/T.REC"]
prototype = "W/T.REC x"
short = "Sets recording state (0/1)"

["W/T.PLAY"]
prototype = "W/T.PLAY playback"
short = "Set the playback state. -1 will flip playback direction"

["W/T.REV"]
prototype = "W/T.REV"
short = "Reverse the direction of playback"

["W/T.SPEED"]
prototype = "W/T.SPEED n d"
short = "Set speed as a rate, calculated by `n` / `d` (numerator/denominator). Negative values are reverse (s16V)"

["W/T.FREQ"]
prototype = "W/T.FREQ f"
short = "Set speed as a 'frequency' (s16V) style value `f`. Maintains reverse state"

["W/T.ERASE.LVL"]
prototype = "W/T.ERASE.LVL level"
short = "Strength of erase head when recording. 0 is overdub, 1 is overwrite. Opposite of feedback (s16V)"

["W/T.MONITOR.LVL"]
prototype = "W/T.MONITOR.LVL gain"
short = "Level of input passed directly to output (s16V)"

["W/T.REC.LVL"]
prototype = "W/T.REC.LVL gain"
short = "Level of input material recorded to tape (s16V)"

["W/T.ECHOMODE"]
prototype = "W/T.ECHOMODE x"
short = "Set to 1 to playback before erase. 0 (default) erases first"

["W/T.LOOP.START"]
prototype = "W/T.LOOP.START"
short = "Set the current time as the beginning of a loop"

["W/T.LOOP.END"]
prototype = "W/T.LOOP.END"
short = "Set the current time as the loop end, and jump to start"

["W/T.LOOP.ACTIVE"]
prototype = "W/T.LOOP.ACTIVE x"
short = "Set the state of looping (0/1)"

["W/T.LOOP.SCALE"]
prototype = "W/T.LOOP.SCALE x"
short = "Multiply (positive) or divide(negative) loop brace by `x`. Zero resets to original window (s8)"

["W/T.LOOP.NEXT"]
prototype = "W/T.LOOP.NEXT dir"
short = "Move loop brace forward/backward by length of loop. Pos = fwd, neg = bkwd. 0 jumps to loop start (eg. retriggers). (s8)"

["W/T.TIME"]
prototype = "W/T.TIME sec sub"
short = "Move playhead to an arbitrary location on tape. `sec` is a whole number of seconds, `sub` is subseconds where 1V = 1 sec. Uses 2 args because TT only supports 16bit args. (s16V)"

["W/T.SEEK"]
prototype = "W/T.SEEK sec sub"
short = "Move playhead relative to current position. `sec` is a whole number of seconds, `sub` is subseconds where 1V = 1 sec. Uses 2 args because TT only supports 16bit args. (s16V)"

["W/T.CLEARTAPE"]
prototype = "W/T.CLEARTAPE"
short = "WARNING! Erases all recorded audio on the tape!"
